### ISSUE TITLE
Unexpected Output

### ISSUE THREAD

**Issue by KRiedmiller** [hits-mbm-dev/git-intro#5]
Output: BuzzFizz
Expected Output: FizzBuzz
PlsFix

https://github.com/hits-mbm-dev/git-intro/blob/873b2cb544c860efb0f80bc1197ebd6f6252d56b/examples/fizzbuzz.py#L16-L16

**Comment by jmbuhr** [comment]
I'm on it!

**Comment by jmbuhr** [comment]
Fixed by https://github.com/hits-mbm-dev/git-intro/commit/506face833de54861248494e536d8693f5c0bf5e
